name: Cross-platform CMake Builds

on: [push, pull_request]

jobs:
  build:
    name: Create Debug and Release builds with CMake on Ubuntu, MacOS and Windows
    runs-on: ${{ matrix.os }}
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install latest CMake
        uses: lukka/get-cmake@latest

      - name: Run CMake (generation and build) for Debug config
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtBasic"
          cmakeBuildType: "Debug"
          buildDirectory: "${{ github.workspace }}/Debug"

      - name: Run the debug executable for testing
        run: ${{ github.workspace }}/Debug/run-tests

      - name: Run CMake (generation and build) for Release config
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtBasic"
          cmakeBuildType: "Release"
          buildDirectory: "${{ github.workspace }}/Release"

      - name: Run the release executable for testing
        run: ${{ github.workspace }}/Release/run-tests
